
<!DOCTYPE html>
<html>
<head>
    <title>Adwinit Shop</title>
</head>
<body>
<h1>Adwinit Shop</h1><hr>
<h4>Авторизация</h4>
<form action="/login" method="post">
    Эл. почта: <input type="email" name="username"><br><br>
    Пароль: <input type="password" name="password"><br><br>
    <input type="hidden" name="_csrf" value="${_csrf.token}">
    <input type="submit" value="Вход"/>
    <br>
</form>
<a href="/registration">Зарегистрироваться</a>

</body>
<br><br>
<footer>
    Vadim Kharovyuk  1993-2024 &copy;
</footer>
</html>